travis:
  secure:
    BINSTAR_TOKEN: dZu/rupBw+zGpW+6xkCUbFFPUiCArgypiFJAbo289TxaP0t5lcJleaEueUt7Y3VGStwAMAuFk2Xsq6/uR+3yQ71wmUEBWsMIlDoq05uvjkmm5PD8dyhvJAhItpP49VbE1+gfvHNRzPFr9lbig3SqolRslcTWkv0JtZGYOTsyLA34eBMH3l5JprPHzUWLzLx5guX4/VsY35daEghSD5PfxENdEHXW6I9sYvkONH8DDCgjVvueb35e9QrDcceLjOcOqPfZ5MM9b3I7fl+yK6pVBbx4Vta3EJrwniBC5gEZSEzeqGAs0oLutBNFpNLwJX3AVQOWZYcTEFzp3xA+ka6HHkz1rpXm1ixL/CwGtHWk1l0ZoS9AZ5QDODbNEYS6OLJ0UGHiLGVz2pl+JGc0fQBntWicrc3ZIoJ871EDEMHoaBo/i2Ugd2Oms06Mf+XS2aE1615d1OEUZ+SrotEwSw6kxzh43POcdGNdbSQ9RzSrH4AiY7snMRHTmVlyoaUyrmBTIu5eBkO+PC8Cyj04kkQJumSpFFlS8neT0LShPc6dpWjwf8sfyOqjeuaQj3YnFGEW9DrwFHPnm6vwvqyE6Y916zGp2gQsy59t7DSAz8+OI2jx/TTyGUASMWf+CBU542Jd8Paok1JWXyEYhQCTYaUSmsetQZUtl911AbjPXRHFAuE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
