travis:
  secure:
    BINSTAR_TOKEN: lKtyxmo0tFOGubPPnptN9VT4h9MimnRRS/cac8IxxdRLGvG6rlaXstxIKeVVM8x8nc+Ad63Bi9cTahfpsQml0h+vxci8Fm1ykoEnqgfZT78bWxbWn9Cjab/l9x9JKd9YhrsFBrG2wpKvmumZAM83v0kT4FEqIfWV8HCaWFYbMA5U/Tsop8YnfPdYxolFvjwBjwntiOnO4BomYp7ml8ETe9rH9wMrAcWDHfCzjQLTjh/yCHqXI8V7loKRRqlFLlxkI4cQFQviqwr1G0RJVoV02j7Z4dezDAfubRzeL2NwY3xhPFV1WiGSqMIsm05rg89L9BFBfSTnu8bbIFFy+snFWh1mQUNGsfJJh9Qa11kmNgbwgmoF10vJaEIosYrsCw3jzYinVWLNwqHjwxYgm9XpRCatSQgcpuv3FXsy1m6ePFww0q1rWqN6Kea/wVV4ZQyadNIRm2BgtA/KThn9Yn9r86gOhJN3DU22OjKx/dlzQ6CdBCCa/mzNp7mSFLwyk8w1qiqQBOq6FwswYh5RRtsFMUm+7KAhzx82dyMZ4byidvjQC0earNmRvx3Cq8nONOTmQZTYmxNtwCn9opHrGCznXuTHIjJznWi1E2hIH6exak0UgLp8StibkJR7nPN1n8qOytj5j9oc9Ru4GyIidzefD78Ss8yyyjHe44p76cQDRbA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
